### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by saschanaz** [amccreight/heapgraph#27]
Not a fun task, yeah 🥲

**Comment by saschanaz** [comment]
Hmm, I see Rust ports are there, so maybe the task is to finish it instead?

**Comment by amccreight** [comment]
The problem with the Rust port is there are lots of niche features I've added to find_roots over the years that are kind of annoying to reimplement, so I never got around to it. But yeah, it would be nice if the Rust version worked. Porting to Python 3 is probably still a lot easier.

**Comment by amccreight** [comment]
Also, if you or anybody are looking at this, don't worry about any of the scripts except those used for find_roots.py (which includes a launcher script and two scripts to parse the GC and CC logs). The rest of it isn't used very much. There's also a lot of stuff around making GraphViz output that hasn't been useful for years that could probably be removed.

**Comment by amccreight** [comment]
I ran 2to3 on the various scripts used by find_roots, and it seemed to work, so I marked this as fixed. There was a little bit of weirdness in the output that I had to fix.
